name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: gitlab_analyzer_test
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Type check
        run: npm run typecheck
        
      - name: Lint check
        run: npm run lint
        
      - name: Build
        run: npm run build
        
      - name: Run database migrations
        run: npm run db:migrate
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: gitlab_analyzer_test
          DB_USERNAME: test_user
          DB_PASSWORD: test_password
          DB_SSL: false
          GITLAB_TOKEN: dummy_token_for_testing
        
      - name: Test (including database tests)
        run: npm test
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: gitlab_analyzer_test
          DB_USERNAME: test_user
          DB_PASSWORD: test_password
          DB_SSL: false
          GITLAB_TOKEN: dummy_token_for_testing